[project]
name = "tfm-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdel-mechanics",
    "pdel-mechanics-notebooks",
]

[tool.uv.sources]
pdel-mechanics = { path = "../../pdel-mechanics", editable = true }
pdel-mechanics-notebooks = { path = "../../pdel-mechanics/notebooks", editable = true }

[dependency-groups]
dev = [
    "ruff>=0.15.17",
    "ty>=0.0.49",
]
