"""Collect the presenter notes from every `next_slide(notes=...)` call and emit
a Markdown document, grouped by section.

We run the real `Defense.construct` with note-collection mode enabled (see
`scenes.base`): `SlideScene` records notes instead of rendering, `play` and
`wait` become no-ops and no window opens, so this is fast and headless.

Usage (from tfm/presentation/):

    uv run python scripts/collect_notes.py            # writes defense-notes.md
    uv run python scripts/collect_notes.py out.md     # custom output path
"""

import os
import sys
from pathlib import Path

# Enable collection mode before importing anything that reads the flag.
os.environ["COLLECT_NOTES"] = "1"

# Run relative to the presentation root so `import scenes...` and asset paths work.
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
os.chdir(ROOT)

from main import Defense  # noqa: E402
from scenes.base import INLINE_TRANSITION, MARKER, note_sections  # noqa: E402


HEADER = (
    "<!-- AUTO-GENERATED by scripts/collect_notes.py -- do not edit by hand. -->\n"
    "<!-- Regenerate with: uv run python scripts/collect_notes.py -->\n"
)

# Warning shown in rendered views too (the HTML comment above is invisible there).
BANNER = (
    "> [!WARNING]\n"
    "> Auto-generated from the `next_slide(notes=...)` calls in `scenes/`.\n"
    "> Do not edit by hand; run `uv run python scripts/collect_notes.py` to regenerate."
)


def _labeled_transition(n: int) -> str:
    """The inline transition marker with a reference number tucked inside it,
    e.g. "<>" becomes "<[3]>"."""
    mid = len(INLINE_TRANSITION) // 2
    return f"{INLINE_TRANSITION[:mid]}[{n}]{INLINE_TRANSITION[mid:]}"


def to_paragraphs(notes: list[dict], refs: list[tuple]) -> list[str]:
    """Turn a section's notes into paragraphs. Each [...] marker becomes an
    INLINE_TRANSITION; when one note ends with a transition and the next begins
    with one, they are the same logical slide clicked in the middle, so we merge
    them into one paragraph. Every note gets a reference number placed exactly
    where it starts: leading the paragraph, or inside the transition marker that
    joins it. Its source location is appended to `refs` as (n, file, line)."""
    paragraphs: list[str] = []
    for note in notes:
        text = MARKER.sub(INLINE_TRANSITION, note["text"]).strip()
        if not text:
            continue
        n = len(refs) + 1
        refs.append((n, note["file"], note["line"]))
        if (
            paragraphs
            and paragraphs[-1].endswith(INLINE_TRANSITION)
            and text.startswith(INLINE_TRANSITION)
        ):
            rest = text[len(INLINE_TRANSITION):].lstrip()
            head = paragraphs[-1][: -len(INLINE_TRANSITION)]
            paragraphs[-1] = f"{head}{_labeled_transition(n)} {rest}"
        else:
            paragraphs.append(f"[{n}] {text}")
    return paragraphs


def build_markdown() -> str:
    lines = [HEADER, "# Defense presenter notes", "", BANNER, ""]
    refs: list[tuple] = []
    for section in note_sections:
        paragraphs = to_paragraphs(section["notes"], refs)
        if not paragraphs:
            continue
        lines.append(f"## {section['name']}")
        lines.append("")
        for paragraph in paragraphs:
            lines.append(paragraph)
            lines.append("")

    if refs:
        lines.append("---")
        lines.append("")
        for n, file, line in refs:
            lines.append(f"[{n}]: {file}:{line}")
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    scene = Defense(window=None, skip_animations=True)
    scene.setup()
    scene.construct()

    out = Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "defense-notes.md"
    out.write_text(build_markdown())
    print(f"Wrote {out} ({len(note_sections)} sections).")


if __name__ == "__main__":
    main()
