[keys.normal."space"."m"]
o = [":pipe-to ./manim-send.sh 'uv run manimgl %{file_path_absolute} -se %{cursor_line}'"]
p = "@F@xvf@<space>y:pipe-to ./manim-send.sh 'checkpoint_paste()'<ret>"
l = "@<space>y:pipe-to ./manim-send.sh 'checkpoint_paste()'<ret>"
k = "@<space>y:pipe-to ./manim-send.sh 'checkpoint_paste(skip=True)'<ret>"
s = "@F@xvf@<space>y:pipe-to ./manim-send.sh 'checkpoint_paste(skip=True)'<ret>"



