[parallel]
watch-open: watch open

note name:
    latexmk -pdf notes/{{name}}.tex && open .build/{{name}}.pdf

build:
    latexmk -pdf main.tex
    
watch:
    watchexec -e tex latexmk -pdf main.tex

[linux]
open:
    xdg-open .build/main.pdf &> /dev/null

[macos]
open:
    open .build/main.pdf
